# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff0987c693dd85989ef0f9d361804b7690ccc75a2941d02253213c6d5a6b365bd33f3a10ef12a577d0d145d8a7f3962957071041b52468b2b4f2e592b5140705

test:
  secret_key_base: 1c7ef1de72981ed1095309128e7c62dc37fe731cef77555f0cb9db1d52e159e77fa0f3a63b3e430dd491c0d917c8d33aaac6aacee1f08ef670e31ae8bd31de81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
